language: node_js
node_js:
  - "8.17.0"

script:
  # using jest --coverage also runs the tests so this will cut down CI time
  - npm test

# Allow Travis tests to run in containers.
sudo: false

notifications:
  email: true
